42/textual enhancement
AxonIQ/axoniq-library-site pull request #43
Opened 2024-10-04 19:49 UTC by SaraTorrey

This PR addresses issue #42 to improve the text of the docs.

2024-10-07 13:43 UTC, smcvb commented on content/legacy_docs_af/modules/ROOT/pages/index.adoc
> +NOTE: The Axon Documentation contains documentation for Axon Framework 4.8 onwards. The menu on the left links to the documentation for previous versions.
```suggestion
NOTE: The Axon Documentation contains documentation for Axon Framework 4.10 onwards. The menu on the left links to the documentation for previous versions.
```

2024-10-07 13:43 UTC, smcvb commented on content/legacy_docs_as/modules/ROOT/pages/index.adoc
> +NOTE: The Axon Documentation contains documentation for Axon Server 4.8 onwards. The menu on the left links to the documentation for previous versions.
```suggestion
NOTE: The Axon Documentation contains documentation for Axon Server 2024.1 onwards. The menu on the left links to the documentation for previous versions.
```

2024-10-07 13:43 UTC, smcvb requested changes
Although it's not a change you made, the referred to version on the legacy docs pages is wrong.

2024-10-07 19:26 UTC, SaraTorrey commented
@smcvb made the requested changes. Thank you for catching those. Let me know if I need to change anything else.

2024-10-08 06:56 UTC, CodeDrivenMitch commented
Since the merge was complex, I did it for you @SaraTorrey, hope you don't mind

2024-10-08 07:50 UTC, smcvb approved these changes
My concerns have been addressed, hence I'm approving this pull request.

2024-10-08 08:04 UTC, merged