fixed linter issues
AxonIQ/axoniq-library-site pull request #5
Opened 2023-09-19 12:34 UTC by bruceaxoniq

fixed contractions and passive style

2023-09-20 13:31 UTC, azzazzel reviewed
@bruceaxoniq Everything looks good except for the playbook and Vale terms changes.

2023-09-20 13:31 UTC, azzazzel commented on playbook-dev.yaml
Let's keep the `playbook-dev.yaml` as a reference in the repo. 
If you need a custom build just copy it under some other name and use that locally instead.

2023-09-20 13:31 UTC, azzazzel commented on playbook-dev.yaml
> +  #  start_paths: ['localLinks/giftcard-demo/docs/*', '!localLinks/giftcard-demo/docs/_playbook']
I guess you know that, but by commenting those out, you build only the content in this repo, and thus, that is the only content the prose linter is checking. 

You really need those to check the errors in the other repos.

2023-09-20 13:31 UTC, azzazzel commented on vale/Vocab/Names_Terms/accept.txt
I added those to the Vale rules. This file will be overwritten by the production build every time as we have `update_styles: true` there.

2023-09-20 13:37 UTC, azzazzel requested changes
@bruceaxoniq  can you pleas update the PR according to the previous comments

2023-09-28 09:32 UTC, bruceaxoniq commented
@azzazzel I updated the PR to remove the files that were supposed to stay local on my machine.

2023-10-06 12:16 UTC, azzazzel approved these changes

2023-10-06 12:19 UTC, merged